version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PASSWORD: mysql

  db:
    image: mysql:5
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  bundle:
    driver: local
  mysql-data:
    driver: local
