---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  rails_app.conf: |
    upstream app {
      server localhost:3000;
    }

    server {
      listen 80 default_server;
      server_name _;
      root /app;

      location / {
        proxy_pass http://app/;
      }
    }
