---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    app.kubernetes.io/name: {{ include "sample.name" . }}
    helm.sh/chart: {{ include "sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  rails_app.conf: |
    upstream app {
      server localhost:3000;
    }

    server {
      listen {{ .Values.service.port }} default_server;
      server_name _;
      root /app;

      location / {
        proxy_pass http://app/;
      }
    }
