apiVersion: batch/v1
kind: Job
metadata:
  name: rails-db-create-migrate-{{ include "sample.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "sample.name" . }}
    helm.sh/chart: {{ include "sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    spec:
      containers:
      - name: rails
        image: "{{ .Values.image.rails.repository }}:{{ .Values.image.rails.tag }}"
        command: ["bundle",  "exec", "rails", "db:create", "db:migrate", "--trace"]
        env:
        - name: DB_HOST
          value: {{ include "sample.mysqlHost" .}}
        - name: DB_PASSWORD
          value: root
      restartPolicy: Never
