---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample.name" . }}
  labels:
    app: {{ include "sample.name" . }}
    app.kubernetes.io/name: {{ include "sample.name" . }}
    helm.sh/chart: {{ include "sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sample.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sample.name" . }}
        app.kubernetes.io/name: {{ include "sample.name" . }}
        helm.sh/chart: {{ include "sample.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
        imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-conf
      - name: rails
        image: "{{ .Values.image.rails.repository }}:{{ .Values.image.rails.tag }}"
        imagePullPolicy: {{ .Values.image.rails.pullPolicy }}
        {{- if .Values.localVolumes }}
        volumeMounts:
        {{- range .Values.localVolumes }}
        - mountPath: {{ .mountPath }}
          name: {{ .name }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.railsPort }}
        env:
        - name: DB_HOST
          value: {{ include "sample.mysqlHost" .}}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rails-secret-{{ include "sample.name" . }}
              key: db_password
      volumes:
      {{- if .Values.localVolumes }}
      {{- range .Values.localVolumes }}
      - name: {{ .name }}
        hostPath:
          path: {{ .hostPath }}
      {{- end }}
      {{- end }}
      - name: nginx-conf
        configMap:
          name: nginx-conf-{{ include "sample.name" . }}
          items:
          - key: rails_app.conf
            path: rails_app.conf
