---
{{- if .Values.localStorage.enabled -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-{{ include "sample.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "sample.name" . }}
    helm.sh/chart: {{ include "sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- end }}

---

{{- if .Values.localStorage.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-data-{{ include "sample.name" . }}
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-{{ include "sample.name" . }}
  local:
    path: /mnt/disks/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        {{- range .Values.nodeSelectors }}
        - key: {{ .name }}
          operator: In
          values:
          - {{ .value }}
        {{- end }}
{{- end }}

---
{{- if .Values.localStorage.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-{{ include "sample.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "sample.name" . }}
    helm.sh/chart: {{ include "sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage-{{ include "sample.name" . }}
  resources:
    requests:
      storage: 1Gi
{{- end }}
