---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample.name" . }}
  labels:
    app: {{ include "sample.name" . }}
    app.kubernetes.io/name: {{ include "sample.name" . }}
    helm.sh/chart: {{ include "sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    app: {{ include "sample.name" . }}
    app.kubernetes.io/name: {{ include "sample.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.service.port }}

---
{{- if .Values.localStorage.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample.mysqlHost" .}}
  labels:
    app: mysql
    app.kubernetes.io/name: {{ include "sample.name" . }}
    helm.sh/chart: {{ include "sample.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: 3306
    name: {{ include "sample.mysqlHost" .}}
  clusterIP: None
  selector:
    app: mysql
    app.kubernetes.io/name: {{ include "sample.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
